-- USERS/KULLANICILAR
CREATE TABLE USERS(
ID NUMBER,
USERNAME_ VARCHAR2(50),
PASSWORD_ VARCHAR2(50),
NAMESURNAME VARCHAR2(100),
EMAIL VARCHAR2(100),
GENDER VARCHAR2(6),
BIRTHDATE DATE,
CREATEDDATE DATE,
TELNR1 VARCHAR2(15),
TELNR2 VARCHAR2(15)
);


-- ADDRESS/ADRES
CREATE TABLE ADDRESS(
ID NUMBER,
USERID NUMBER,
COUNTRYID NUMBER,
CITYID NUMBER,
TOWNID NUMBER,
DISTRICTID NUMBER,
POSTALCODE VARCHAR2(10),
ADDRESSTEXT VARCHAR2(500)
);

-- COUNTRIES/ÜLKELER
CREATE TABLE COUNTRIES(
ID NUMBER,
COUNTRY VARCHAR2(50)
);

-- CITIES/ŞEHİRLER
CREATE TABLE CITIES(
ID NUMBER,
COUNTRYID NUMBER,
CITY VARCHAR2(50)
);

-- TOWNS/İLÇE
CREATE TABLE TOWNS(
ID NUMBER,
CITYID NUMBER,
TOWN VARCHAR2(50)
);

-- DISTRICTS/SEMT		
CREATE TABLE DISTRICTS(
ID NUMBER,
TOWNID NUMBER,
DISTRICT VARCHAR2(50)
);

-- ITEMS/ÖĞELER		
CREATE TABLE ITEMS(
ID NUMBER,
ITEMCODE VARCHAR2(50),
ITEMNAME VARCHAR2(100),
UNITPRICE NUMBER,
CATEGORY1 VARCHAR2(50),
CATEGORY2 VARCHAR2(50),
CATEGORY3 VARCHAR2(50),
CATEGORY4 VARCHAR2(50),
BRAND VARCHAR2(50)
);

-- ORDERS/EMİRLER		
CREATE TABLE ORDERS(
ID NUMBER,
USERID NUMBER,
DATE_ DATE,
TOTALPRICE NUMBER,
STATUS_ NUMBER,
ADDRESSID NUMBER
);

-- ORDERDETAILS/SİPARİŞ DETAYLARI		
CREATE TABLE ORDERDETAILS(
ID NUMBER,
ORDERID NUMBER,
ITEMID NUMBER,
AMOUNT NUMBER,
UNITPRICE NUMBER,
LINETOTAL NUMBER
);

-- INVOICE/FATURA		
CREATE TABLE INVOICE(
ID NUMBER,
ORDERID NUMBER,
DATE_ DATE,
ADDRESSID NUMBER,
CARGOFICHENO VARCHAR2(20),
TOTALPRICE NUMBER
);

-- INVOICEDETAIL/FATURA DETAYI		
CREATE TABLE INVOICEDETAIL(
ID NUMBER,
INVOICEID NUMBER,
ORDERDETAILID NUMBER,
ITEMID NUMBER,
AMOUNT NUMBER,
UNITPRICE NUMBER,
LINETOTAL NUMBER
);

-- PAYMENTS/ÖDEMELER		
CREATE TABLE PAYMENTS(
ID NUMBER,
ORDERID NUMBER,
PAYMENTTYPE NUMBER,
DATE_ DATE,
ISOK NUMBER,
APPROVECODE VARCHAR2(100),
PAYMENTTOTAL NUMBER
);

